name: Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        export PATH=$PATH:~/go/bin
        
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r27
        add-to-path: true
        link-to-sdk: true
        local-cache: true

    - name: Restore Android Symlinks
      run: |
        directory="${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin"
        find "$directory" -type l | while read link; do
            current_target=$(readlink "$link")
            new_target="$directory/$(basename "$current_target")"
            ln -sf "$new_target" "$link"
            echo "Changed $(basename "$link") from $current_target to $new_target"
        done

    - name: Build
      run: |
         mkdir -p assets data
         bash gen_assets.sh download
         cp -v data/*.dat assets/
         gomobile init
         go mod tidy
         gomobile bind -v -androidapi 21 -trimpath -ldflags='-s -w -buildid=' ./
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Upload AndroidLibXrayLite to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./libv2ray*r
        tag: ${{ github.event.inputs.release_tag }}
        file_glob: true
    
    - name: Prepare source repository
      env: 
        TAG: ${{ github.event.inputs.release_tag }}
      run: |
        git clone https://github.com/2dust/v2rayNG.git
        cd v2rayNG/AndroidLibXrayLite
        git submodule update --init --recursive
        git submodule foreach "git fetch origin && git checkout $TAG"

        if [[ -n "$(git status -s)" ]]; then
          echo "needs_update=true" >> $GITHUB_ENV
        else
          echo "needs_update=false" >> $GITHUB_ENV
        fi

    - name: Push changes to update branch
      if: env.needs_update == 'true'
      env:
        GH_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        git remote add myfork https://github.com/${{ github.actor }}/v2rayNG.git

        git checkout -b update-libxraylite-${{ github.event.inputs.release_tag }}
        git add .
        git add .github
        git commit -m "Update AndroidLibXrayLite to ${{ github.event.inputs.release_tag }}"
        git push myfork update-libxraylite-${{ github.event.inputs.release_tag }}

    #
